language: python
python:
  - "3.6"
# command to install dependencies

cache: pip
install:
 - pip install -r requirements.txt
 
script: 
 - python helloTravis.py
 - python GameState.py
 - python Discovery.py
 - python NLC.py
 - pytest
 
